using './main.bicep'

param storageAccountName = 'nordicholidays'
param keyVaultName = 'kv-nordicholidays'
param functionAppName = 'nordic-holidays-api'
param appInsightsName = 'nordic-holidays-api'
param staticWebAppName = 'nordicholidays'
param location = 'westeurope'
param nodeVersion = '22'
param storageAccountSku = 'Standard_LRS'
param staticWebAppSku = 'Free'
