      - name: Package API
        working-directory: api
        run: |
          mkdir -p deploy/dist/src
          cp package.json deploy/
          cp package-lock.json deploy/ || true
          cp -r host.json deploy/ || true
          cp -r dist/src deploy/dist/src
          cd deploy
          zip -r ../../api.zip .
    