import type { CitySuggestion } from '../data/cities'
import type { Accommodation, CulinaryRegion, Stop } from '../types'
import type { RegionConfig } from './types'

const cities: CitySuggestion[] = [
  { id: 'new-york-us', name: 'New York', countryCode: 'US', countryName: 'United States', region: 'New York', lat: 40.7128, lng: -74.0060, aliases: ['NYC', 'New York City', 'Manhattan'] },
  { id: 'los-angeles-us', name: 'Los Angeles', countryCode: 'US', countryName: 'United States', region: 'California', lat: 34.0522, lng: -118.2437, aliases: ['LA'] },
  { id: 'chicago-us', name: 'Chicago', countryCode: 'US', countryName: 'United States', region: 'Illinois', lat: 41.8781, lng: -87.6298, aliases: [] },
  { id: 'houston-us', name: 'Houston', countryCode: 'US', countryName: 'United States', region: 'Texas', lat: 29.7604, lng: -95.3698, aliases: [] },
  { id: 'phoenix-us', name: 'Phoenix', countryCode: 'US', countryName: 'United States', region: 'Arizona', lat: 33.4484, lng: -112.0740, aliases: [] },
  { id: 'philadelphia-us', name: 'Philadelphia', countryCode: 'US', countryName: 'United States', region: 'Pennsylvania', lat: 39.9526, lng: -75.1652, aliases: ['Philly'] },
  { id: 'san-antonio-us', name: 'San Antonio', countryCode: 'US', countryName: 'United States', region: 'Texas', lat: 29.4241, lng: -98.4936, aliases: [] },
  { id: 'san-diego-us', name: 'San Diego', countryCode: 'US', countryName: 'United States', region: 'California', lat: 32.7157, lng: -117.1611, aliases: [] },
  { id: 'dallas-us', name: 'Dallas', countryCode: 'US', countryName: 'United States', region: 'Texas', lat: 32.7767, lng: -96.7970, aliases: [] },
  { id: 'san-jose-us', name: 'San Jose', countryCode: 'US', countryName: 'United States', region: 'California', lat: 37.3382, lng: -121.8863, aliases: [] },
  { id: 'austin-us', name: 'Austin', countryCode: 'US', countryName: 'United States', region: 'Texas', lat: 30.2672, lng: -97.7431, aliases: [] },
  { id: 'jacksonville-us', name: 'Jacksonville', countryCode: 'US', countryName: 'United States', region: 'Florida', lat: 30.3322, lng: -81.6557, aliases: [] },
  { id: 'fort-worth-us', name: 'Fort Worth', countryCode: 'US', countryName: 'United States', region: 'Texas', lat: 32.7555, lng: -97.3308, aliases: [] },
  { id: 'columbus-us', name: 'Columbus', countryCode: 'US', countryName: 'United States', region: 'Ohio', lat: 39.9612, lng: -82.9988, aliases: [] },
  { id: 'charlotte-us', name: 'Charlotte', countryCode: 'US', countryName: 'United States', region: 'North Carolina', lat: 35.2271, lng: -80.8431, aliases: [] },
  { id: 'san-francisco-us', name: 'San Francisco', countryCode: 'US', countryName: 'United States', region: 'California', lat: 37.7749, lng: -122.4194, aliases: ['SF', 'Frisco'] },
  { id: 'indianapolis-us', name: 'Indianapolis', countryCode: 'US', countryName: 'United States', region: 'Indiana', lat: 39.7684, lng: -86.1581, aliases: ['Indy'] },
  { id: 'seattle-us', name: 'Seattle', countryCode: 'US', countryName: 'United States', region: 'Washington', lat: 47.6062, lng: -122.3321, aliases: [] },
  { id: 'denver-us', name: 'Denver', countryCode: 'US', countryName: 'United States', region: 'Colorado', lat: 39.7392, lng: -104.9903, aliases: ['Mile High City'] },
  { id: 'boston-us', name: 'Boston', countryCode: 'US', countryName: 'United States', region: 'Massachusetts', lat: 42.3601, lng: -71.0589, aliases: ['Beantown'] },
  { id: 'el-paso-us', name: 'El Paso', countryCode: 'US', countryName: 'United States', region: 'Texas', lat: 31.7619, lng: -106.4850, aliases: [] },
  { id: 'nashville-us', name: 'Nashville', countryCode: 'US', countryName: 'United States', region: 'Tennessee', lat: 36.1627, lng: -86.7816, aliases: ['Music City', 'Nash Vegas'] },
  { id: 'detroit-us', name: 'Detroit', countryCode: 'US', countryName: 'United States', region: 'Michigan', lat: 42.3314, lng: -83.0458, aliases: ['Motown'] },
  { id: 'oklahoma-city-us', name: 'Oklahoma City', countryCode: 'US', countryName: 'United States', region: 'Oklahoma', lat: 35.4676, lng: -97.5164, aliases: ['OKC'] },
  { id: 'portland-or-us', name: 'Portland', countryCode: 'US', countryName: 'United States', region: 'Oregon', lat: 45.5152, lng: -122.6784, aliases: ['PDX', 'Portland OR'] },
  { id: 'las-vegas-us', name: 'Las Vegas', countryCode: 'US', countryName: 'United States', region: 'Nevada', lat: 36.1699, lng: -115.1398, aliases: ['Vegas', 'LV'] },
  { id: 'memphis-us', name: 'Memphis', countryCode: 'US', countryName: 'United States', region: 'Tennessee', lat: 35.1495, lng: -90.0490, aliases: ['Bluff City'] },
  { id: 'louisville-us', name: 'Louisville', countryCode: 'US', countryName: 'United States', region: 'Kentucky', lat: 38.2527, lng: -85.7585, aliases: [] },
  { id: 'baltimore-us', name: 'Baltimore', countryCode: 'US', countryName: 'United States', region: 'Maryland', lat: 39.2904, lng: -76.6122, aliases: ['Charm City'] },
  { id: 'milwaukee-us', name: 'Milwaukee', countryCode: 'US', countryName: 'United States', region: 'Wisconsin', lat: 43.0389, lng: -87.9065, aliases: ['MKE', 'Brew City'] },
  { id: 'albuquerque-us', name: 'Albuquerque', countryCode: 'US', countryName: 'United States', region: 'New Mexico', lat: 35.0844, lng: -106.6504, aliases: ['ABQ', 'Duke City'] },
  { id: 'tucson-us', name: 'Tucson', countryCode: 'US', countryName: 'United States', region: 'Arizona', lat: 32.2226, lng: -110.9747, aliases: [] },
  { id: 'fresno-us', name: 'Fresno', countryCode: 'US', countryName: 'United States', region: 'California', lat: 36.7378, lng: -119.7871, aliases: [] },
  { id: 'sacramento-us', name: 'Sacramento', countryCode: 'US', countryName: 'United States', region: 'California', lat: 38.5816, lng: -121.4944, aliases: ['SAC', 'Sactown'] },
  { id: 'kansas-city-us', name: 'Kansas City', countryCode: 'US', countryName: 'United States', region: 'Missouri', lat: 39.0997, lng: -94.5786, aliases: ['KCMO', 'KCK'] },
  { id: 'mesa-us', name: 'Mesa', countryCode: 'US', countryName: 'United States', region: 'Arizona', lat: 33.4152, lng: -111.8315, aliases: [] },
  { id: 'atlanta-us', name: 'Atlanta', countryCode: 'US', countryName: 'United States', region: 'Georgia', lat: 33.7490, lng: -84.3880, aliases: ['ATL', 'Hotlanta'] },
  { id: 'omaha-us', name: 'Omaha', countryCode: 'US', countryName: 'United States', region: 'Nebraska', lat: 41.2565, lng: -95.9345, aliases: [] },
  { id: 'colorado-springs-us', name: 'Colorado Springs', countryCode: 'US', countryName: 'United States', region: 'Colorado', lat: 38.8339, lng: -104.8214, aliases: [] },
  { id: 'raleigh-us', name: 'Raleigh', countryCode: 'US', countryName: 'United States', region: 'North Carolina', lat: 35.7796, lng: -78.6382, aliases: ['City of Oaks'] },
  { id: 'miami-us', name: 'Miami', countryCode: 'US', countryName: 'United States', region: 'Florida', lat: 25.7617, lng: -80.1918, aliases: ['MIA'] },
  { id: 'minneapolis-us', name: 'Minneapolis', countryCode: 'US', countryName: 'United States', region: 'Minnesota', lat: 44.9778, lng: -93.2650, aliases: ['MSP', 'City of Lakes'] },
  { id: 'cleveland-us', name: 'Cleveland', countryCode: 'US', countryName: 'United States', region: 'Ohio', lat: 41.4993, lng: -81.6944, aliases: ['CLE', 'Forest City'] },
  { id: 'wichita-us', name: 'Wichita', countryCode: 'US', countryName: 'United States', region: 'Kansas', lat: 37.6872, lng: -97.3301, aliases: [] },
  { id: 'arlington-tx-us', name: 'Arlington', countryCode: 'US', countryName: 'United States', region: 'Texas', lat: 32.7357, lng: -97.1081, aliases: [] },
  { id: 'new-orleans-us', name: 'New Orleans', countryCode: 'US', countryName: 'United States', region: 'Louisiana', lat: 29.9511, lng: -90.0715, aliases: ['NOLA', 'The Big Easy'] },
  { id: 'bakersfield-us', name: 'Bakersfield', countryCode: 'US', countryName: 'United States', region: 'California', lat: 35.3733, lng: -119.0187, aliases: [] },
  { id: 'salt-lake-city-us', name: 'Salt Lake City', countryCode: 'US', countryName: 'United States', region: 'Utah', lat: 40.7608, lng: -111.8910, aliases: ['SLC'] },
  { id: 'honolulu-us', name: 'Honolulu', countryCode: 'US', countryName: 'United States', region: 'Hawaii', lat: 21.3069, lng: -157.8583, aliases: ['HNL'] },
  { id: 'anaheim-us', name: 'Anaheim', countryCode: 'US', countryName: 'United States', region: 'California', lat: 33.8366, lng: -117.9143, aliases: [] },
  { id: 'tampa-us', name: 'Tampa', countryCode: 'US', countryName: 'United States', region: 'Florida', lat: 27.9506, lng: -82.4572, aliases: ['TPA'] },
  { id: 'santa-ana-us', name: 'Santa Ana', countryCode: 'US', countryName: 'United States', region: 'California', lat: 33.7455, lng: -117.8677, aliases: [] },
  { id: 'st-louis-us', name: 'St. Louis', countryCode: 'US', countryName: 'United States', region: 'Missouri', lat: 38.6270, lng: -90.1994, aliases: ['Saint Louis', 'Gateway City'] },
  { id: 'pittsburgh-us', name: 'Pittsburgh', countryCode: 'US', countryName: 'United States', region: 'Pennsylvania', lat: 40.4406, lng: -79.9959, aliases: ['Steel City', 'PGH'] },
  { id: 'cincinnati-us', name: 'Cincinnati', countryCode: 'US', countryName: 'United States', region: 'Ohio', lat: 39.1031, lng: -84.5120, aliases: ['Cincy'] },
  { id: 'orlando-us', name: 'Orlando', countryCode: 'US', countryName: 'United States', region: 'Florida', lat: 28.5383, lng: -81.3792, aliases: ['MCO', 'City Beautiful'] },
  { id: 'st-paul-us', name: 'St. Paul', countryCode: 'US', countryName: 'United States', region: 'Minnesota', lat: 44.9537, lng: -93.0900, aliases: ['Saint Paul'] },
  { id: 'newark-us', name: 'Newark', countryCode: 'US', countryName: 'United States', region: 'New Jersey', lat: 40.7357, lng: -74.1724, aliases: ['EWR', 'Brick City'] },
  { id: 'lincoln-us', name: 'Lincoln', countryCode: 'US', countryName: 'United States', region: 'Nebraska', lat: 40.8136, lng: -96.7026, aliases: ['Star City'] },
  { id: 'buffalo-us', name: 'Buffalo', countryCode: 'US', countryName: 'United States', region: 'New York', lat: 42.8864, lng: -78.8784, aliases: ['BUF', 'Queen City'] },
  { id: 'anchorage-us', name: 'Anchorage', countryCode: 'US', countryName: 'United States', region: 'Alaska', lat: 61.2181, lng: -149.9003, aliases: ['ANC'] },
  { id: 'burlington-us', name: 'Burlington', countryCode: 'US', countryName: 'United States', region: 'Vermont', lat: 44.4759, lng: -73.2121, aliases: ['BTV'] },
  { id: 'portland-me-us', name: 'Portland', countryCode: 'US', countryName: 'United States', region: 'Maine', lat: 43.6589, lng: -70.3112, aliases: ['Portland ME', 'PWM'] },
  { id: 'charleston-sc-us', name: 'Charleston', countryCode: 'US', countryName: 'United States', region: 'South Carolina', lat: 32.7765, lng: -79.9311, aliases: ['Charleston SC', 'Chucktown'] },
  { id: 'savannah-us', name: 'Savannah', countryCode: 'US', countryName: 'United States', region: 'Georgia', lat: 32.0809, lng: -81.0912, aliases: ['Hostess City'] },
  { id: 'asheville-us', name: 'Asheville', countryCode: 'US', countryName: 'United States', region: 'North Carolina', lat: 35.5951, lng: -82.5515, aliases: ['AVL', 'Land of the Sky'] },
  { id: 'boise-us', name: 'Boise', countryCode: 'US', countryName: 'United States', region: 'Idaho', lat: 43.6150, lng: -116.2023, aliases: ['BOI', 'City of Trees'] },
  { id: 'billings-us', name: 'Billings', countryCode: 'US', countryName: 'United States', region: 'Montana', lat: 45.7833, lng: -108.5007, aliases: ['Magic City', 'BIL'] },
  { id: 'cheyenne-us', name: 'Cheyenne', countryCode: 'US', countryName: 'United States', region: 'Wyoming', lat: 41.1400, lng: -104.8202, aliases: ['Magic City of the Plains'] },
  { id: 'fargo-us', name: 'Fargo', countryCode: 'US', countryName: 'United States', region: 'North Dakota', lat: 46.8772, lng: -96.7898, aliases: ['FAR'] },
  { id: 'sioux-falls-us', name: 'Sioux Falls', countryCode: 'US', countryName: 'United States', region: 'South Dakota', lat: 43.5511, lng: -96.7003, aliases: ['FSD'] },
  { id: 'des-moines-us', name: 'Des Moines', countryCode: 'US', countryName: 'United States', region: 'Iowa', lat: 41.5868, lng: -93.6250, aliases: ['DSM', 'Hartford of the West'] },
  { id: 'madison-us', name: 'Madison', countryCode: 'US', countryName: 'United States', region: 'Wisconsin', lat: 43.0731, lng: -89.4012, aliases: ['MSQ', 'Mad City'] },
]

const defaultStops: Stop[] = [
  {
    id: 1, days: '1–2', dates: 'Sep 1–2', dest: 'San Francisco', region: 'California',
    coords: [-122.4194, 37.7749], tags: ['city', 'iconic'], nights: 2,
    desc: "Start your Pacific Coast Highway adventure in the City by the Bay. Ride a cable car past Painted Ladies, walk through Chinatown, and cycle the Golden Gate Bridge to Sausalito. Alcatraz at dusk and a Mission District burrito round out day two.",
    highlights: ['Golden Gate Bridge & Sausalito ferry', 'Alcatraz Island night tour', 'Cable cars & Lombard Street', 'Mission District murals & burritos', 'Ferry Building food hall'],
    from: 'Start', km: 0, time: '—', zoom: 12, pitch: 50, bearing: -20,
  },
  {
    id: 2, days: '3', dates: 'Sep 3', dest: 'Big Sur', region: 'California',
    coords: [-121.8078, 36.2704], tags: ['nature', 'scenic'], nights: 1,
    desc: "The most spectacular stretch of Highway 1 clings to cliffs above the Pacific. Stop at Half Moon Bay and Santa Cruz for boardwalk vibes, then wind through redwood canyons to reach Big Sur's dramatic coastline. McWay Falls plunges straight onto the beach.",
    highlights: ['Highway 1 Big Sur cliffs', 'McWay Falls overlook', 'Bixby Creek Bridge', 'Pfeiffer Big Sur State Park redwoods', 'Nepenthe cliffside restaurant'],
    from: 'San Francisco', km: 240, time: '5 hrs', zoom: 11, pitch: 55, bearing: 30,
  },
  {
    id: 3, days: '4–5', dates: 'Sep 4–5', dest: 'Los Angeles', region: 'California',
    coords: [-118.2437, 34.0522], tags: ['city', 'iconic'], nights: 2,
    desc: "Cruise into LA via Malibu's coastline. Two days to explore: the Hollywood Walk of Fame, Griffith Observatory at sunset, Santa Monica Pier, and the Getty Center. Drive Mulholland Drive at dusk for the classic LA sprawl panorama.",
    highlights: ['Griffith Observatory & Hollywood Sign', 'Santa Monica Pier & Route 66 end', 'Getty Center art & gardens', 'Mulholland Drive sunset', 'Venice Beach boardwalk'],
    from: 'Big Sur', km: 350, time: '6 hrs', zoom: 11, pitch: 45, bearing: 10,
  },
  {
    id: 4, days: '6', dates: 'Sep 6', dest: 'San Diego', region: 'California',
    coords: [-117.1611, 32.7157], tags: ['city', 'beach'], nights: 1,
    desc: "SoCal's laid-back finale: perfect beaches, world-class Mexican food, and Balboa Park's Spanish colonial architecture. Sunset Cliffs delivers the best sundown on the West Coast. Gaslamp Quarter comes alive after dark.",
    highlights: ['Balboa Park & museums', 'La Jolla Cove sea lions', 'Sunset Cliffs', 'Gaslamp Quarter nightlife', 'Authentic California burritos & fish tacos'],
    from: 'Los Angeles', km: 190, time: '2.5 hrs', zoom: 12, pitch: 40, bearing: 5,
  },
  {
    id: 5, days: '7', dates: 'Sep 7', dest: 'Phoenix', region: 'Arizona',
    coords: [-112.0740, 33.4484], tags: ['city', 'desert'], nights: 1,
    desc: "Leave the coast and climb into the Sonoran Desert. Phoenix's saguaro-studded landscape is unlike anywhere else in America. Camelback Mountain hike at dawn, then Scottsdale's art galleries and desert botanical garden in the evening.",
    highlights: ['Desert Botanical Garden', 'Camelback Mountain hike', 'Old Town Scottsdale', 'Saguaro cactus forests', 'Sonoran hot dog (bacon-wrapped)'],
    from: 'San Diego', km: 560, time: '5.5 hrs', zoom: 11, pitch: 45, bearing: -10,
  },
  {
    id: 6, days: '8', dates: 'Sep 8', dest: 'Grand Canyon', region: 'Arizona',
    coords: [-112.1401, 36.0544], tags: ['nature', 'iconic'], nights: 1,
    desc: "Nothing prepares you for the Grand Canyon's scale — a mile deep, 277 miles long. Arrive for sunset at Mather Point, then sunrise at Desert View Watchtower. Drive the rim or hike below on the Bright Angel Trail. One of the planet's great natural wonders.",
    highlights: ['Mather Point sunset & sunrise', 'Bright Angel Trail descent', 'Desert View Watchtower', 'Rim Drive viewpoints', 'El Tovar historic lodge'],
    from: 'Phoenix', km: 370, time: '4 hrs', zoom: 11, pitch: 60, bearing: 15,
  },
  {
    id: 7, days: '9–10', dates: 'Sep 9–10', dest: 'Las Vegas', region: 'Nevada',
    coords: [-115.1398, 36.1699], tags: ['city', 'iconic'], nights: 2,
    desc: "From natural wonder to neon spectacle. The Strip is an adult playground of themed mega-resorts, world-class shows, and 24-hour everything. Detour to Red Rock Canyon for desert hiking, or Hoover Dam for engineering awe. Dine like royalty — Vegas has more Michelin chefs than any US city.",
    highlights: ['The Strip at night', 'Bellagio fountains & conservatory', 'Red Rock Canyon scenic drive', 'Hoover Dam tour', 'Sphere & Fremont Street Experience'],
    from: 'Grand Canyon', km: 280, time: '4.5 hrs', zoom: 12, pitch: 50, bearing: -5,
  },
  {
    id: 8, days: '11', dates: 'Sep 11', dest: 'Zion National Park', region: 'Utah',
    coords: [-113.0263, 37.2982], tags: ['nature', 'scenic'], nights: 1,
    desc: "Utah's mightiest national park: sandstone cliffs glow crimson and gold as the sun moves across the canyon. The Narrows slot canyon hike (wading through the Virgin River) and Angels Landing ridge scramble are unforgettable. Free shuttle system keeps the canyon car-free.",
    highlights: ["Angels Landing (permit required)", 'The Narrows river hike', 'Zion Canyon Scenic Drive', 'Canyon Overlook Trail', 'Watchman sunset'],
    from: 'Las Vegas', km: 260, time: '2.5 hrs', zoom: 12, pitch: 65, bearing: 20,
  },
  {
    id: 9, days: '12–13', dates: 'Sep 12–13', dest: 'Salt Lake City', region: 'Utah',
    coords: [-111.8910, 40.7608], tags: ['city', 'historic'], nights: 2,
    desc: "Temple Square's granite spires and Tabernacle Choir, then the Great Salt Lake's alien shoreline. Antelope Island offers free-roaming bison against a mirrored salt flat backdrop. The city's food scene is surprisingly strong — local pastrami burgers and fry sauce are a Utah institution.",
    highlights: ['Temple Square & Tabernacle', 'Great Salt Lake & Antelope Island bison', 'Natural History Museum of Utah', 'Bonneville Salt Flats detour', 'Red Iguana Mexican (local legend)'],
    from: 'Zion National Park', km: 510, time: '4.5 hrs', zoom: 11, pitch: 40, bearing: 0,
  },
  {
    id: 10, days: '14–15', dates: 'Sep 14–15', dest: 'Yellowstone', region: 'Wyoming',
    coords: [-110.5885, 44.4280], tags: ['nature', 'iconic'], nights: 2,
    desc: "America's first national park sits atop a supervolcano. Old Faithful erupts on schedule, but Grand Prismatic Spring's rainbow waters and Mammoth Hot Springs' travertine terraces steal the show. Bison jam traffic, elk graze in meadows, grizzlies fish in rivers. Two days barely covers the upper loop.",
    highlights: ['Old Faithful & Upper Geyser Basin', 'Grand Prismatic Spring', 'Mammoth Hot Springs terraces', 'Lamar Valley wildlife safari', 'Grand Canyon of the Yellowstone'],
    from: 'Salt Lake City', km: 540, time: '5 hrs', zoom: 10, pitch: 50, bearing: 10,
  },
  {
    id: 11, days: '16', dates: 'Sep 16', dest: 'Bozeman', region: 'Montana',
    coords: [-111.0385, 45.6770], tags: ['city', 'nature'], nights: 1,
    desc: "Montana's coolest college town — craft breweries, a dinosaur museum, and the Gallatin River's blue-ribbon fly fishing. Main Street's Western storefronts hide excellent farm-to-table dining. The Bridger Range backdrop earns Bozeman its 'most livable place' reputation. The perfect end to an epic cross-country road trip.",
    highlights: ['Museum of the Rockies (T. rex skeletons)', 'Main Street breweries & dining', 'Gallatin River fly fishing', 'Bridger Bowl scenic chairlift', 'Big Sky detour'],
    from: 'Yellowstone', km: 160, time: '2 hrs', zoom: 12, pitch: 45, bearing: -15,
  },
]

const defaultCulinary: CulinaryRegion[] = [
  {
    name: 'California Wine & Farm-to-Table',
    region: 'Napa Valley & Central Coast',
    icon: '🍷',
    color: '#722f37',
    desc: "California's agricultural abundance drives America's most influential food movement. From Napa's world-class Cabernet to the Central Coast's Pinot Noir, the farm-to-table ethos was born here. Farmers' markets overflow year-round with heirloom produce, and the Mission burrito is a SF institution.",
    must: ['Mission burrito (San Francisco)', 'Napa Valley Cabernet Sauvignon', 'Central Coast Pinot Noir', 'Farmers market heirloom tomatoes', 'Sourdough bread from Boudin', 'Dungeness crab (in season)'],
  },
  {
    name: 'Texas BBQ & Tex-Mex',
    region: 'Austin, Dallas & San Antonio',
    icon: '🥩',
    color: '#8b2500',
    desc: "Texas BBQ is a religion — slow-smoked brisket over post oak for 12+ hours, served on butcher paper with white bread and pickles. The Tex-Mex border culture brings breakfast tacos, queso flameado, and mesquite-grilled meats. Austin's food truck scene pushes the tradition forward.",
    must: ['Smoked brisket (post oak)', 'Breakfast tacos', 'Pecan-smoked pork ribs', 'Chili con carne', 'Fajitas over mesquite', 'Texas sheet cake'],
  },
  {
    name: 'Louisiana Cajun & Creole',
    region: 'New Orleans & Acadiana',
    icon: '🦐',
    color: '#c58a00',
    desc: "New Orleans is America's most distinctive food city — French, Spanish, African, and Caribbean influences in every pot. Gumbo, jambalaya, and étouffée are holy. Crawfish boils define spring. Beignets and chicory coffee at Café du Monde never miss. This is food that tells a story of survival and celebration.",
    must: ['Gumbo (filé or okra)', 'Crawfish boil', 'Shrimp & grits', 'Étouffée', 'Beignets & chicory coffee', 'Oysters Rockefeller', 'Po-boy (dressed)'],
  },
  {
    name: 'Pacific Northwest Seafood',
    region: 'Seattle & Portland',
    icon: '🐟',
    color: '#2f5d7a',
    desc: "The cold, clean waters of the Pacific Northwest yield some of the world's best seafood. Copper River salmon, Dungeness crab, Penn Cove mussels, and oysters from Samish Bay. Pike Place Market is Seattle's living larder. Add Oregon Pinot Noir, coffee culture, and foraging (chanterelles, morels) and you have a singular regional cuisine.",
    must: ['Copper River sockeye salmon', 'Dungeness crab', 'Penn Cove mussels', 'Raw oysters (Samish Bay)', 'Geoduck sashimi', 'Marionberry pie', 'Stumptown coffee'],
  },
  {
    name: 'Midwest Steak & Heartland',
    region: 'Kansas City, Omaha & Chicago',
    icon: '🌽',
    color: '#9b6b00',
    desc: "The Midwest is America's breadbasket — corn-fed beef, wheat fields, and dairy country. Omaha and Kansas City are steakhouse capitals. Chicago's deep-dish and Italian beef are legendary. The State Fair circuit celebrates everything fried-on-a-stick. Simple, generous, hearty cooking rooted in immigrant traditions.",
    must: ['Dry-aged ribeye (Omaha)', 'Kansas City burnt ends', 'Chicago deep-dish pizza', 'Italian beef sandwich (dipped)', 'Butterburger (Culver\'s)', 'Corn on the cob', 'Fried cheese curds'],
  },
  {
    name: 'New York Pizza & Deli',
    region: 'New York City',
    icon: '🍕',
    color: '#cc5500',
    desc: "New York's food is about immigrants perfecting traditions in tight quarters. Thin-crust pizza folded in half, pastrami on rye at century-old delis, bagels boiled then baked, and chopped cheese from bodegas. The dollar slice is democratic. Katz's, Lombardi's, Russ & Daughters — these are institutions, not restaurants.",
    must: ['New York slice (foldable thin crust)', 'Pastrami on rye (Katz\'s)', 'Bagel with lox & schmear', 'Chopped cheese from a bodega', 'Black & white cookie', 'Egg cream'],
  },
]

const defaultAccommodations: Accommodation[] = [
  { dest: 'San Francisco', type: 'Boutique Hotel', policy: 'mod', bath: true, terrace: false, note: 'Union Square or Nob Hill — walk to cable cars. Avoid Tenderloin area.' },
  { dest: 'Big Sur', type: 'Riverside Lodge / Cabin', policy: 'cond', bath: true, terrace: true, note: 'Very limited lodging — book months ahead. Ventana or Glen Oaks.' },
  { dest: 'Los Angeles', type: 'Hotel / Airbnb', policy: 'free', bath: true, terrace: true, note: 'West Hollywood or Santa Monica for walkable neighborhoods.' },
  { dest: 'San Diego', type: 'Boutique Hotel', policy: 'free', bath: true, terrace: true, note: 'Gaslamp Quarter or Mission Beach — rooftop pools common.' },
  { dest: 'Phoenix', type: 'Resort / Hotel', policy: 'free', bath: true, terrace: true, note: 'Scottsdale resorts are legendary for pools & spas.' },
  { dest: 'Grand Canyon', type: 'Lodge / Cabin', policy: 'cond', bath: true, terrace: false, note: 'South Rim lodges book up 6+ months ahead. Tusayan as backup.' },
  { dest: 'Las Vegas', type: 'Casino Resort', policy: 'free', bath: true, terrace: true, note: 'Strip resorts — mid-week rates are half of weekend.' },
  { dest: 'Zion National Park', type: 'Lodge / Inn', policy: 'cond', bath: true, terrace: true, note: 'Springdale has the best options near the park entrance.' },
  { dest: 'Salt Lake City', type: 'Hotel / Airbnb', policy: 'free', bath: true, terrace: false, note: 'Downtown or Sugar House — both walkable and safe.' },
  { dest: 'Yellowstone', type: 'Park Lodge / Cabin', policy: 'cond', bath: true, terrace: false, note: 'In-park lodging books a year ahead. West Yellowstone, MT as backup.' },
  { dest: 'Bozeman', type: 'Boutique Hotel / B&B', policy: 'free', bath: true, terrace: true, note: 'Downtown Main Street — walk to breweries and dining.' },
]

export const us: RegionConfig = {
  brandName: 'RouteKit',
  tagline: 'Coast to coast road trip planning',
  countries: [{ code: 'US', labelKey: 'country.us' }],
  defaultCountry: 'US',
  cities,
  seasonData: [
    ['pacific northwest', { icon: '🌲', noteKey: 'season.pacificNorthwest' }],
    ['pacific', { icon: '🌊', noteKey: 'season.pacific' }],
    ['west coast', { icon: '🌊', noteKey: 'season.pacific' }],
    ['california', { icon: '☀️', noteKey: 'season.california' }],
    ['west', { icon: '🏜️', noteKey: 'season.west' }],
    ['southwest', { icon: '🌵', noteKey: 'season.southwest' }],
    ['desert', { icon: '🌵', noteKey: 'season.southwest' }],
    ['mountain', { icon: '🏔️', noteKey: 'season.mountain' }],
    ['rockies', { icon: '🏔️', noteKey: 'season.mountain' }],
    ['midwest', { icon: '🌾', noteKey: 'season.midwest' }],
    ['plains', { icon: '🌾', noteKey: 'season.midwest' }],
    ['south', { icon: '🎸', noteKey: 'season.south' }],
    ['deep south', { icon: '🎸', noteKey: 'season.south' }],
    ['southeast', { icon: '🎸', noteKey: 'season.south' }],
    ['texas', { icon: '🤠', noteKey: 'season.texas' }],
    ['florida', { icon: '🌴', noteKey: 'season.florida' }],
    ['gulf', { icon: '🌴', noteKey: 'season.florida' }],
    ['northeast', { icon: '🏙️', noteKey: 'season.northeast' }],
    ['new england', { icon: '🍂', noteKey: 'season.newEngland' }],
    ['atlantic', { icon: '⛵', noteKey: 'season.northeast' }],
    ['alaska', { icon: '🐻', noteKey: 'season.alaska' }],
    ['hawaii', { icon: '🌺', noteKey: 'season.hawaii' }],
  ],
  defaultStops,
  defaultCulinary,
  defaultAccommodations,
  mapDefaults: { center: [-98.5, 39.8], zoom: 4 },
  heroContent: {
    badgeKey: 'hero.badge',
    subtitleKey: 'hero.subtitle',
    metaDays: 'hero.metaDays',
    metaKm: 'hero.metaKm',
    metaDestinations: 'hero.metaDestinations',
    metaFoodRegions: 'hero.metaFoodRegions',
  },
  footerTaglineKey: 'footer.tagline',
}
